[package]
name = "tkom-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0.0"
utf8-read = "0.4.0"
rust_decimal = "1.23.0"
rust_decimal_macros = "1.23"